# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='monitor_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=50)),
                ('test', models.CharField(max_length=50)),
            ],
        ),
    ]
